version: "3"
services:
  management1:
    image: mysql-cluster
    command:
      - ndb_mgmd
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.2
  ndb1:
    image: mysql-cluster
    restart: always
    command: ndbd --initial-start --connect-string="172.28.0.2:1186"
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.3
  ndb2:
    image: mysql-cluster
    restart: always
    command: ndbd --initial-start --connect-string="172.28.0.2:1186"
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.4
  mysql1:
    image: mysql-cluster
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bdteste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_HOST: '%'
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.10
  mysql2:
    image: mysql-cluster
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bdteste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_HOST: ''
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.9
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql1:db
    networks:
      mysqlcluster:
        

networks:
  mysqlcluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254
